### ISSUE TITLE
.in registry prohibits privacy protect

### ISSUE THREAD

**Issue by rootkea** [moul/grpcbin#35]
> **3.  Proxy/Privacy  Services:**  Any  kind  of  proxy  services  are  not  allowed,  and  if  the  data  is  wrong  or  masked  out  by  any  proxy/ privilege protection services, the Registrant shall not be recognized as the owner of the domain name.

Source: https://www.registry.in/system/files/Terms_and_Conditions_for_Registrants_1_0.pdf

I suggest we move to privacy protect friendly registry or else the current .in domain might get seized/closed.

**Comment by moul** [comment]
good to know, thank you @rootkea :+1: 

I just took grpcbin.org and will switch to it if needed :)

**Comment by rootkea** [comment]
Happy to help! :-)
